env:
  browser: true
  es2021: true
extends:
  - airbnb
  - "plugin:@typescript-eslint/recommended"
  - "plugin:import/typescript"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
  - import
rules:
  no-console: off
  linebreak-style: off
  semi:
    - error
    - always
  quotes:
    - error
    - single
  no-use-before-define: off
  "@typescript-eslint/no-use-before-define":
    - error
  "@typescript-eslint/explicit-module-boundary-types": off
  import/extensions:
    - error
    - always
    - tsx: never
   arrow-parens: off
   
