version: "3.8"
services:
  app: # Application
    build: .
    networks:
      - mq-network

  mq: # RabbitMQ server
    image: rabbitmq:3-management
    ports:
      - 5672:5672 # RabbitMQ default port
      - 15672:15672 # RabitMQ management port
    networks:
      - mq-network

networks:
  mq-network:
